package com.jesvardo.app.network.model

data class ModelResponseVehicleListBooking(
    var id : String,
    var destination : String,
    var destination_lat : Int,
    var destination_long : Int,
    var device_id : String,
    var discount_code : String,
    var discount_code_amount : String,
    var security_deposit : Int,
    var from_date : String,
    var to_date : String,
    var from_time : String,
    var to_time : String,
    var created : String,
    var user : String,
    var listing : String,
    var security_deposit_due_date : String,
    var status : String,
    var trip_type : String,
    var withdraw_reason : String,
    var booking_amount : Int,
    var cutomer_message : String,
    var owner_email : String,
    var booking_placed_on : String,
    var trip : String,
    var reservation_amount : Int,
    var reservation_amount_due : Int,
    var reservation_amount_due_date : String,
    var delivery_location : String,
    var delivery_location_lat : Int,
    var delivery_location_long : Int,
    var booking_id : String,
    var checkin_completed : Boolean,
    var checkout_completed : Boolean,
    var created_by : String,
    var updated_by : String
)

